name: react-on-comment
on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    name: Check comment for /publish
    runs-on: ubuntu-latest
    steps:
      - name: Check command
        id: check-command
        uses: xt0rted/slash-command-action@v1
        with:
          command: publish
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write
          repo-token: ${{ secrets.GH_TOKEN }}

  create-comment:
        name: Create comment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create comment
              uses: peter-evans/create-or-update-comment@v1
              with:
                token: ${{ secrets.GH_TOKEN }}
                issue-number: ${{ github.event.issue.number }}
                body: |
                  Hello @${{ github.event.comment.user.login }}! Thanks for your comment.

  